config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  

  
  get '/profile' => 'profile#show', as: 'profile'
  get '/profile/followers' => 'profile#followers', as: 'profile_followers'
  get '/profile/followings' => 'profile#followings', as: 'profile_followings'

  get '/settings' => 'home#settings', as: 'settings'

  get '/settings/avatar' => 'avatar#edit', as: 'avatar'
  put 'settings/avatar/save/:id' => 'avatar#save', as: 'avatar_save'
  # get '/settings/avatar' => 'avatar#new', as: 'new_avatar'
  # post '/settings/avatar/create' => 'avatar#create', as: 'avatar_create'

  get '/user/:id/followers' => 'user#followers', as: 'user_followers'
  get '/user/:id/followings' => 'user#followings', as: 'user_followings'
  resources :user, :except => [:new, :create, :index]
  post '/user/:id/friend-up' =>"user#follow", as: 'follow'
  delete '/user/:id/unfollow' =>"user#unfollow", as: 'unfollow'

  get 'post/followings' => 'post#followings', as: 'followings_posts'
  get 'post/liked' => 'post#liked', as: 'liked_posts'
  resources :post do
    resources :comment, :except => [:show, :index, :new]
  end
  post '/post/:id/like' =>"post#like", as: 'like_post'
  delete '/post/:id/unlike' =>"post#unlike", as: 'unlike_post'

end

app/views/partials/_avatar.html.erb
<%size = "206x206" unless size%>
<%cls =  '' unless cls%>
<%if not resource.avatar.file.nil?%>
	<%= link_to image_tag(resource.avatar, class: "img-thumbnail #{cls}"),
	user_path(resource.username)%>
<%else%>
	<%= link_to image_tag("/no-avatar.png", class: "img-thumbnail #{cls}"),
		user_path(resource.username)%>
<%end%>

app/views/partials/_bar.html.erb
<%if bars && access%>
	<ul class="nav right nav-pills">
		<%bars.each do |key, value|%>
			<li role="presentation" class="<%=active?([key])%>"><a href="<%=key%>"><%=value%></a></li>
		<%end%>
	</ul>
<%end%>

app/views/partials/_comments.html.erb
<%if user_signed_in?%>
	<%no_comments_message = "Your comment will be the first"%>
<%else%>
	<%no_comments_message = "No comments"%>
<%end%>
<%if comments.length > 0%>

	<%comments.each do |comment|%>
		<div class="panel panel-default comment-panel">
		  <div class="panel-heading">

		  	<%=render partial: "partials/avatar", 
		  	locals: {resource: user_by_id(comment.author_id), 
		  		cls: "img-circle thumbnail-sm"}%>
	  		<%= link_to_user(user_by_id(comment.author_id))%> said:

  			<%if user_signed_in?%>
	  			<%if comment.author_id == current_user.id%>
	  				<small class="right">
			  			<a data-confirm="Are you shure?" rel="nofollow" 
			  				data-method="delete" 
			  				href="/post/<%=$post.id%>/comment/<%=comment.id%>" 
			  				data-confirm="Are you sure ?">
			  				<%=icon('remove')%>		
							</a>
  					</small>
					<%end%>
				<%end%>
				<div class="arrow-up comment-arrow-up">
				</div>
			</div>
		  <div class="content"><%=breaklines_on(comment.text)%>
		  </div>
			<small class="right">
				<%=hint(comment.created_at)%>
			</small>
		</div>	
	<% end %>
<%else%>
	<h5><%= hint(no_comments_message)%></h5>
<%end%>

app/views/partials/_emoticons.html.erb
<div id="emotions">
		<span class="emotion">&#128515;</span>
		<span class="emotion">&#128518;</span>
		<span class="emotion">&#128521;</span>
		<span class="emotion">&#128522;</span>
		<span class="emotion">&#128525;</span>
		<span class="emotion">&#128526;</span>
		<span class="emotion">&#128527;</span>
		<span class="emotion">&#128528;</span>
		<span class="emotion">&#128541;</span>
		<span class="emotion">&#128544;</span>
		<span class="emotion">&#128551;</span>
		<span class="emotion">&#128557;</span>
		<span class="emotion">&#128558;</span>
		<span class="emotion">&#128564;</span>
		<span class="emotion">&#128565;</span>
		<span class="emotion">&#128570;</span>

</div>

app/views/partials/_errors.html.erb
<%if resource.errors.any?%>

	<div class="alert alert-warning">
		<% resource.errors.full_messages.each do |message|%>
			<center><li><%=message%></li></center>
		<%end%>
	</div>
<%end%>

app/views/partials/_follow-panels.html.erb
<div class="panel panel-default">
  	<div class="panel-heading">
	  	<a href="<%=user_followers_path(resource.username)%>">
		    <span class="panel-title">Followers </span>
		    <span class="badge"><%=followers.length%></span>
		</a>
  	</div>
  	<div class="panel-body">
		<%if followers.length > 0%>
			<% followers.each do |follower| %>
				<%= link_to_user (follower) %><br>
			<%end%>
		<%else%>
			<%=hint("No followers yet")%>
		<%end%>				
	</div>
</div><hr>

<div class="panel panel-default">
  <div class="panel-heading">
  	<a href="<%=user_followings_path(resource.username)%>">
	    <span class="panel-title">Followings </span>
	    <span class="badge"><%=followings.length%></span>
	</a>
  </div>
  <div class="panel-body">
		<%if followings.length > 0%>
			<% followings.each do |following| %>
				<%= link_to_user (following) %><br>
			<%end%>
		<%else%>
			<%=hint("No followings yet")%>
		<%end%>				
	</div>
</div>

app/views/partials/_header.html.erb
<%if @header%>
  <nav class="shadow container border header-bar navbar-default">

      <%if width == "small"%>
          <div class="col-xs-9 hamurz main-color header-text">
            <%= @header %>
          </div>
          <%if bars && @access%>
            <div class="col-xs-3">
              <button type="button" class="navbar-toggle" data-toggle="collapse" 
              data-target="#bars">
                <span class="icon-bar"></span>
              </button>
            </div>
          <%end%>
        <div class="collapse navbar-collapse" id="bars">
          <%=render partial: 'partials/bar', locals: {bars: bars, access: @access} %>
        </div>
      <%end%>

      <%if width == "large"%>
          <div class="col-xs-6 hamurz main-color header-text">
            <%= @header %>
          </div>
          <div class="col-xs-6">
            <%=render partial: 'partials/bar', locals: {bars: bars, access: @access} %>
          </div>
      <%end%>
  </nav>
<%end%>

app/views/partials/_navbar.html.erb
<nav class="shadow navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <%= link_to image_tag("/logo.png", class: 'logo'), root_path %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false">
        <span class="icon-bar"></span>
      </button>
      <%= link_to "doodle blog", root_path, class: "hamurz navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav">
        <li class="<%=active?([followings_posts_path, liked_posts_path, post_index_path])%>">
          <a href="<%=post_index_path%>">
            <%=icon("list-alt")%> Post feed
          </a>
        <li class="<%=active?([new_post_path])%>">
          <a href="<%=new_post_path%>">
            <%=icon("pencil")%> Write a post
          </a>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <%if user_signed_in?%>

          <li class="<%=active?([user_followers_path(current_user.username)])%>">
            <%=link_to "Followers", user_followers_path(current_user.username)%>
          <li class="<%=active?([user_followings_path(current_user.username)])%>">
            <%=link_to "Followings", user_followings_path(current_user.username)%>
          <li class="dropdown">
            <a href="<%=profile_path%>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=icon("user")%> <%=current_user.username%> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="<%=profile_path%>">
                  <%=icon("file")%> Your profile
                </a>
              </li>
              <li>
                <a href="/settings"><%=icon("cog")%></span> Settings</a>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="<%=destroy_user_session_path%>" data-method="delete">
                  <%=icon("log-out")%> Sign out
                </a>
            </ul>
          </li>
        <%else%>
          <li class="<%=active?([new_user_session_path])%>">
            <a href="<%=new_user_session_path%>">
            <%=icon("log-in")%> Sign in</a>
          </li>
          <li class="<%=active?([new_user_registration_path])%>">
            <a href="<%=new_user_registration_path%>">
            <%=icon("check")%> Sign up</a>
          </li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_posts.html.erb
<%avatar = false unless avatar%>

<%if posts.length > 0%>
	<%posts.each do |post|%>
	<%if avatar%>
		<div class="row post-list">
			<div class="avatar col-sm-4 col-md-3 hidden-xs">
				<center>
					<%=link_to(image_tag(post.cover, class:'img-thumbnail'), post_path(post))%>
					<!-- <%=render partial: "partials/avatar", locals: {resource: user_by_id(post.author_id), cls: "img-circle"}%> -->
				</center>
			</div>
			<div class="info col-sm-8 col-md-9">
				<h2><a href="<%=post_path(post)%>"><%=post.title%></a>
				</h2>
				<b>Posted by:</b> <%=link_to_user(user_by_id(post.author_id)) %><br>
				<%=hint("#{post.comments.length} comment(s)")%>
			</div>
		</div>
	<%else%>
		<h2><a href="<%=post_path(post)%>"><%=post.title%></a></h2>
		<b>Posted by:</b> <%=link_to_user(user_by_id(post.author_id)) %><br>
		<%=hint("#{post.comments.length} comment(s)")%>
	<%end%>


	<div id="<%=post.id%>" class="post-text" expanded="false">
		<%if avatar%>
			<div class="arrow-up hidden-xs"></div>
		<%end%>
		<div class="no-mrgn-btm well well-sm post-well">
			<%=breaklines_on(post.text)%>
		</div>
	</div>

	<center>
		<a target="#<%=post.id%>" class="post-text-fader">
			<%=icon("chevron-down")%>
	    </a>
	</center>
    <hr>
<%end%>
<%else%>
	<%=hint("No posts yet")%>
<%end%>