config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  

  
  get '/profile' => 'profile#show', as: 'profile'
  get '/profile/followers' => 'profile#followers', as: 'profile_followers'
  get '/profile/followings' => 'profile#followings', as: 'profile_followings'

  get '/settings' => 'home#settings', as: 'settings'

  get '/settings/avatar' => 'avatar#edit', as: 'avatar'
  put 'settings/avatar/save/:id' => 'avatar#save', as: 'avatar_save'
  # get '/settings/avatar' => 'avatar#new', as: 'new_avatar'
  # post '/settings/avatar/create' => 'avatar#create', as: 'avatar_create'

  get '/user/:id/followers' => 'user#followers', as: 'user_followers'
  get '/user/:id/followings' => 'user#followings', as: 'user_followings'
  resources :user, :except => [:new, :create, :index]
  post '/user/:id/friend-up' =>"user#follow", as: 'follow'
  delete '/user/:id/unfollow' =>"user#unfollow", as: 'unfollow'

  get 'post/followings' => 'post#followings', as: 'followings_posts'
  get 'post/liked' => 'post#liked', as: 'liked_posts'
  resources :post do
    resources :comment, :except => [:show, :index, :new]
  end
  post '/post/:id/like' =>"post#like", as: 'like_post'
  delete '/post/:id/unlike' =>"post#unlike", as: 'unlike_post'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  
  def index
  end

  def settings
    @header = "settings"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="hamurz">The doodle bloG</h1>
  <p>It's a simple solution for those who wants to blog!</p><br>
  <p>Check some easy tips for a better experience:</p>
  <ul>
  	<li>Sign in or sign up to use all features</li>
  	<li>Use the search to find posts</li>
  	<li>Use toggles to collapse the post's text without openning it</li>
  </ul><br>

  <div class="panel news-panel">
    <div class="panel-heading">
      <h3 class="hamurz">what's new</h3>
    </div>
    <div class="panel-body">
      <ul>
        <li>User's avatars</li>
        <li>Cover on post</li>
        <li>Now you are able to use emoticons!</li>
        <!-- <li>Newrelic-apm gem implemented to collect stats and to hold the app awake by punching it every 5 minutes</li> -->
      </ul>
    </div>
  </div>

  <%if user_signed_in?%>
  	<p><a class="btn btn-default btn-lg" href="<%=post_index_path%>" role="button">Get started</a></p>
  <%else%>
  	<p><a class="btn btn-default btn-lg" href="<%=new_user_session_path%>" role="button">Get started</a></p>
  <%end%>
</div>

app/views/home/my_profile.html.erb
<div class="row">
	<div class="col-md-3 col-sm-4 col-xs-5">
			<%if @avatar%>
				<%= link_to image_tag(@avatar.image.url, class: 'img-thumbnail'), 
				@avatar.image.url, target: '_blank'%>
			<%else%>
				<br><br><br><br>
				<center class="hint">Your photo here</center>
				<br><br><br><br>
			<%end%>
		<hr>

		<div class="border">
			<div class="border">
				<h4>Your followers:</h4><hr>
				<% @followers.each do |follower| %>
					<%= link_to_user (follower) %><br>
				<%end%>
			</div><hr>

			<div class="border">
				<h4>Your followings:</h4><hr>
				<% @followings.each do |following| %>
					<%= link_to_user (following) %>
				<%end%>
			</div>
		</div>
	</div>
	
	<div class="col-md-8 col-sm-8 col-xs-7">	
		<div class="border content">
			<h3><b><%= current_user.username %></b></h3><hr>
			<p><b>Amount of posts: </b><%= current_user.amount_of_posts %></p>
			<p><b>Sign in count: </b><%= current_user.sign_in_count %></p>
			<p><b>Current sign in at:</b> <%= current_user.current_sign_in_at %></p>
			<p><b>Current sign in ip: </b><%= current_user.current_sign_in_ip %></p>
			<p><b>Registered at: </b><%= current_user.created_at %></p>
		</div>
		<br>
		<div class="border content">
			<hr>
			<%@posts.each do |post|%>					
					<h4><a href="<%=post_path(post)%>"><%=post.title%></a></h4>
					<b>Posted by:</b> <%= user_by_id(post.author_id).username %><hr>
			<%end%>
		</div>
	</div>
</div>

app/views/home/settings.html.erb
<div class="list-group">

	<%= link_to "Edit your profile", edit_user_registration_path, class: "list-group-item" %>
	<%= link_to "Upload a avatar", avatar_path, class: "list-group-item" %>

</div>