config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  

  
  get '/profile' => 'profile#show', as: 'profile'
  get '/profile/followers' => 'profile#followers', as: 'profile_followers'
  get '/profile/followings' => 'profile#followings', as: 'profile_followings'

  get '/settings' => 'home#settings', as: 'settings'

  get '/settings/avatar' => 'avatar#edit', as: 'avatar'
  put 'settings/avatar/save/:id' => 'avatar#save', as: 'avatar_save'
  # get '/settings/avatar' => 'avatar#new', as: 'new_avatar'
  # post '/settings/avatar/create' => 'avatar#create', as: 'avatar_create'

  get '/user/:id/followers' => 'user#followers', as: 'user_followers'
  get '/user/:id/followings' => 'user#followings', as: 'user_followings'
  resources :user, :except => [:new, :create, :index]
  post '/user/:id/friend-up' =>"user#follow", as: 'follow'
  delete '/user/:id/unfollow' =>"user#unfollow", as: 'unfollow'

  get 'post/followings' => 'post#followings', as: 'followings_posts'
  get 'post/liked' => 'post#liked', as: 'liked_posts'
  resources :post do
    resources :comment, :except => [:show, :index, :new]
  end
  post '/post/:id/like' =>"post#like", as: 'like_post'
  delete '/post/:id/unlike' =>"post#unlike", as: 'unlike_post'

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes

  validates :title, presence: true
  validates :text, presence: true

  mount_uploader :cover, CoverUploader
  validates_processing_of :cover
  validates_size_of :cover, maximum: 1.megabytes, message: "should weight less than 1Mbit" 

  def self.search(search)
	  if search
	    where('title LIKE ?', "%#{search}%")
	  else
	    all
	  end
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :post_by_params_id, only: [:like, :unlike, :edit, :destroy, :show]
  before_action :author?, only: [:edit, :destroy, :update]
  before_action :post_bars, only: [:index, :followings, :liked]

  def index
    @header = "all posts"
    @posts = Post.search(params[:search]).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  def followings
    @header = "followings' posts"
    followings = Follower.where(follower_id: current_user.id).map(&:user_id)
    @posts = Post.where(author_id: followings).order(created_at: :desc).paginate(page: params[:page], :per_page => 3)
  end

  def liked
    @header = "liked posts"   
    liked = Like.where(author_id: current_user.id).order(created_at: :desc).map(&:post_id)
    @posts = Post.where(id: liked).paginate(page: params[:page], :per_page => 3)
  end

  def new
    @header = "write a new post"
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      flash[:notice] = "Posted successfully."
      redirect_to post_path(@post)
    else
      @header = "write a new post"
      render action: "new"
    end
  end

  def show
    @comment = Comment.new
    @header = $post.title.downcase
    @author = user_by_id($post.author_id)
    @comments = $post.comments.reverse
    @likers = []
    $post.likes.each do |like|
      @likers << user_by_id(like.author_id).username
    end
  end

  def destroy
    $post.destroy
    redirect_to post_index_path
  end

  def edit
    @header = "edit post"
  end

  def update
    $post.title = params[:post][:title]
    $post.text = params[:post][:text]
    $post.cover = params[:post][:cover]
    if $post.save
      flash[:notice] = "Edited successfully."
      redirect_to post_path($post)
    else
      @header = "edit post"
      render action: "edit"
    end
  end

  def like
    $post.likes.create(author_id: current_user.id)
    redirect_to post_path($post)
  end

  def unlike
    $post.likes.where(author_id: current_user.id).take.delete
    redirect_to post_path($post)
  end





  private

  def post_params
    params.require(:post).permit(:title, :text, :cover)
  end

  def author?
    if $post.author_id != current_user.id
      redirect_to post_path($post)
    end
  end

  def post_by_params_id
    $post = Post.find(params[:id])
  end

  def post_bars
    @access = user_signed_in?
    @bars = {
      "#{followings_posts_path}" => "Followings' posts",
      "#{liked_posts_path}" => "Liked posts",
      "#{post_index_path}" => "All posts"
    }
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/edit.html.erb
<%= form_for $post, url: {action: "update"} do |f| %>

	<%=render partial: "/partials/errors", locals: {resource: $post}%>

	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
	<br>
	<%= f.label :text %>
	<%= f.text_area :text, class: 'form-control post-text-field smile-able-input' %>
	<%=render partial: "/partials/emoticons"%>
	<br>
	<%= f.label :cover %>
	<%= f.file_field :cover%>

	<br>
	<%= button_tag(type: 'submit', class: 'btn btn-default') do %>
		<%=icon("ok")%></span> Done
	<%end%>
<%end%>	

app/views/post/followings.html.erb
<%= render partial: 'partials/posts', locals: {posts: @posts, avatar: true} %>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/post/index.html.erb
<%= render partial: 'partials/posts', locals: {posts: @posts, avatar: true} %>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/post/liked.html.erb
<%= render partial: 'partials/posts', locals: {posts: @posts, avatar: true} %>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/post/new.html.erb
<%= form_for @post, url: {action: "create"} do |f| %>

	<%=render partial: "/partials/errors", locals: {resource: @post}%>

	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
	<br>
	<%= f.label :text %>
	<%= f.text_area :text, class: 'form-control post-text-field smile-able-input' %>
	<%=render partial: "/partials/emoticons"%>

	<br>
	<%= f.label :cover %>
	<%= f.file_field :cover%>

	<br>
	<%= button_tag(type: 'submit', class: 'btn btn-default') do %>
		<%=icon("ok")%> Done
	<%end%>
<%end%>

app/views/post/show.html.erb
<div class="post-block
">
	<div class="border row">
		<div class="col-md-9 col-sm-9 col-xs-12 ">
			<div class="well well-lg post">
					<center><h1 class="post-title"><%= $post.title %></h1></center>
					<div class="post-cover-img">
						<center>
							<%= image_tag($post.cover, class: "cover")%>
						</center>
					</div>
				<div class="well-md">
					<%=breaklines_on($post.text)%>
				</div>
			</div>
		</div>
		<div class="col-sm-3 col-xs-12 post-info">
				<div class="border well-sm credits">
					<%=icon('user')%> <b>Author: </b><i><%=link_to_user(@author)%></i><br>
					<%=icon('time')%> <b>Created at: </b><i><%=$post.created_at%></i>
				</div>
				<div class="list-group actions">
					<% if user_signed_in? and @author.id == current_user.id %>
						<a class="list-group-item" data-confirm="Are you shure?" rel="nofollow" data-method="delete" href="<%=post_path($post)%>" data-confirm="Are you sure ?">
						<%=icon("trash")%> Delete
						</a>

						<a class="list-group-item" href="<%=edit_post_path($post)%>">
							<%=icon("pencil")%> Edit
						</a>

					<%else%>
						<% if user_signed_in? and @likers.include?(current_user.username) %>
							<a class="list-group-item" rel="nofollow" data-method="delete"
							href="<%=unlike_post_path($post)%>"><%=icon("thumbs-up", 'color:#337ab7')%> You like it!</a>
						<% else %>
							<a class="list-group-item" data-method="post"
							href="<%=like_post_path($post)%>">
								<%=icon("thumbs-up")%> Like this post!
							</a>
						<%end%>
					<%end%>
				</div>
			<center>
				<a toggle="tooltip" title="<%=@likers.join(', ')%>" style="cursor: pointer">
					<%=@likers.length%>
				</a>
				people like it
			</center>
		</div>
	</div>
</div>
<br>


<%if user_signed_in?%>
	<hr>
	<div class="row">
		<div class="col-md-9">
			<%=  form_for @comment , url: post_comment_index_path($post), method: :post do |f|%>

				<%= f.label :comment%> <%=icon("comment")%>
				<%= f.text_area :text, class: 'form-control post-comment-field smile-able-input' %>
				<%=render partial: "/partials/emoticons"%>
				<br>
				<%= button_tag(type: 'submit', class: 'btn btn-default') do %>
					<%=icon("ok")%> Add a comment
				<%end%>
			<% end %>
		</div>
	</div>
<%end%>

	<div class="row"><hr>
		<div class="col-md-9">

		<%=render partial: "/partials/comments", locals: {comments: @comments}%>

		</div>
	</div>