config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  

  
  get '/profile' => 'profile#show', as: 'profile'
  get '/profile/followers' => 'profile#followers', as: 'profile_followers'
  get '/profile/followings' => 'profile#followings', as: 'profile_followings'

  get '/settings' => 'home#settings', as: 'settings'

  get '/settings/avatar' => 'avatar#edit', as: 'avatar'
  put 'settings/avatar/save/:id' => 'avatar#save', as: 'avatar_save'
  # get '/settings/avatar' => 'avatar#new', as: 'new_avatar'
  # post '/settings/avatar/create' => 'avatar#create', as: 'avatar_create'

  get '/user/:id/followers' => 'user#followers', as: 'user_followers'
  get '/user/:id/followings' => 'user#followings', as: 'user_followings'
  resources :user, :except => [:new, :create, :index]
  post '/user/:id/friend-up' =>"user#follow", as: 'follow'
  delete '/user/:id/unfollow' =>"user#unfollow", as: 'unfollow'

  get 'post/followings' => 'post#followings', as: 'followings_posts'
  get 'post/liked' => 'post#liked', as: 'liked_posts'
  resources :post do
    resources :comment, :except => [:show, :index, :new]
  end
  post '/post/:id/like' =>"post#like", as: 'like_post'
  delete '/post/:id/unlike' =>"post#unlike", as: 'unlike_post'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :followers
  
  mount_uploader :avatar, AvatarUploader
  validates_size_of :avatar, maximum: 1.megabytes, message: "should weight less than 1Mbit" 

  def email_required?
    false
  end

  def email_changed?
    false
  end

  # attr_accessor :login

  # def self.find_for_database_authentication(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  #   elsif conditions.has_key?(:username) || conditions.has_key?(:email)
  #     where(conditions.to_hash).first
  #   end
  # end
 
  validates :username, presence: true, uniqueness: {
  message: "has already been taken" } 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :user_by_params_id
  before_action :get_follow_info, except: [:friend_up, :unfollow]

  def show
    @header = "#{@user.username.downcase}'s page"
    @posts = Post.where(author_id: @user.id).order(created_at: :desc)

  end

  def followers
    @header = "#{@user.username.downcase}'s followers"
  end

  def followings
    @header = "#{@user.username.downcase}'s followings"
  end

  def follow
    @user.followers.create(follower_id: current_user.id)
    redirect_to (user_path(@user.username))
  end

  def unfollow
    @user.followers.where(follower_id: current_user.id).take.delete
    redirect_to (user_path(@user.username))
  end

  private

  def user_by_params_id
    @user = user_by_username(params[:id])
  end

  def get_follow_info

    $followers = []
    Follower.where(user_id: @user.id).find_each do |follower|
      $followers << user_by_id(follower.follower_id)
    end

    $followings = []
     Follower.where(follower_id: @user.id).find_each do |following|
       $followings << user_by_id(following.user_id)
     end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/followers.html.erb
<%if $followers.length > 0%>
	<% $followers.each do |follower|%>
		<div class="col-xs-6 col-sm-4 col-lg-3">
			<%=render partial: "partials/avatar", locals: {resource: follower}%>
			<center>
				<h3 class="hamurz main-color"><b><%= follower.username.downcase %></b></h3>
			</center>
		</div>
	<%end%>
<%else%>
	<h4><%=hint('No followers here')%></h4>
<%end%>

app/views/user/followings.html.erb
<%if $followings.length > 0%>
	<% $followings.each do |following|%>
		<div class="col-xs-6 col-sm-4 col-lg-3">
			<%=render partial: "partials/avatar", locals: {resource: following}%>
			<center>
				<h3 class="hamurz main-color"><b><%= following.username.downcase %></b></h3>
			</center>
		</div>
	<%end%>
<%else%>
	<h4><%=hint('No followings here')%></h4>
<%end%>

app/views/user/show.html.erb
<div class="row">
	<div class="col-md-3 col-sm-5 col-xs-12">
		<center class='avatar'>
			<%=render partial: "partials/avatar", locals: {resource: @user, size: '380x400'}%>
		</center>
		<%if @user != current_user && user_signed_in?%>
			<%if $followers.include?(current_user)%>
				<div class="list-group">
					<a class="list-group-item" rel="nofollow" data-method="delete" href="<%=unfollow_path(@user.username)%>"><%=icon("minus")%> Unfollow
					</a>
				</div>
			<%else%>
				<div class="list-group">
					<a class="list-group-item" rel="nofollow" data-method="post" href="<%=follow_path(@user.username)%>"><%=icon("plus")%> Follow</a>
				</div>
			<%end%>
		<%end%>
	</div>

	<div class="col-md-9 col-sm-7 col-xs-12">
		<div class="border content">
			<h2 class="hamurz main-color"><b><%= @user.username.downcase %></b></h2>
			<hr>
			<p><b>Amount of posts: </b><%= @posts.length %></p>
			<p><b>Registered at: <br></b><%= @user.created_at %></p>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-3 col-sm-5 col-xs-12">

		<%=render partial: 'partials/follow-panels', 
		locals: {followers: $followers, followings: $followings, resource: @user}%>
	</div>
	<div class="col-md-9 col-sm-7 col-xs-12">

		<div class="panel panel-default">
		  <div class="panel-heading">
		    <span class="panel-title"><%=@user.username%>'s posts </span>
		    <span class="badge"><%=@posts.length%></span>
		  </div>
		  <div class="panel-body">
				<%= render partial: 'partials/posts', locals: {posts: @posts} %>			
			</div>
		</div>	
	</div>

</div>